---
- name: Play for backend
  hosts: backend
  roles:
    - backend
  vars_files: ./group_vars/backend.yaml

- name: Play for frontend
  gather_facts: False
  hosts: frontend
  roles:
    - frontend
  vars_files: ./group_vars/frontend.yaml
