---

- name: Add GPG-key for install NodeJS
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    state: present

- name: Add link to NodeJS repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version | default(16) }}.x focal main"
    state: present
    update_cache: yes

- name: Install NodeJS
  apt:
    pkg:
      - nodejs
    state: present

- name: Install http-server
  npm:
    name: http-server
    global: yes

- name: Add user for service
  user:
    name: "{{ frontend_user }}"
    create_home: no
    shell: /sbin/nologin

- name: Create working directory
  file:
    path: "{{ frontend_path }}"
    state: directory
    owner: "{{ frontend_user }}"
    group: "{{ frontend_user }}"
    mode: 0755
    recurse: yes

- name: Download artifact from Nexus repository
  get_url:
    url: "{{ nexus_frontend_url }}/{{ frontend_version }}/sausage-store-{{ frontend_version }}.tar.gz"
    dest: /var/tmp
    username: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    mode: 0755
    timeout: 5

- name: Extract artifact to working directory from archive
  unarchive:
    src: "/var/tmp/sausage-store-{{ frontend_version }}.tar.gz"
    dest: "{{ frontend_path }}"
    copy: no

- name: Set owner and chmode for front_user on front_path
  file:
    path: "{{ frontend_path }}"
    owner: "{{ frontend_user }}"
    group: "{{ frontend_user }}"
    mode: 0755
    recurse: yes

- name: Template for sausage frontend
  template:
    src: sausage-store-frontend.service.j2
    dest: /etc/systemd/system/sausage-store-frontend.service
  notify:
    - Reload systemd
    - Restart frontend
